// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndgpfgntrwukxcygrcdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZ3BmZ250cnd1a3hjeWdyY2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzkwMTQsImV4cCI6MjA2Mzc1NTAxNH0.4iTLlRB3R2uJF45kh4Lx_TCuGedIkurLcBtOIK0Faok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);